# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#inicio"
  weight = 10

[[main]]
  name = "Miembros"
  url = "miembros/"
  weight = 20

[[main]]
  name = "Proyectos"
  url = "proyectos/"
  weight = 30

[[main]]
  name = "Publicaciones y patentes"
  url = "publicaciones/"
  weight = 40

[[main]]
  name = "Tesis"
  url = "tesis/"
  weight = 50

[[main]]
  name = "Participa"
  url = "participa/"
  weight = 60

[[main]]
  name = "Contacto"
  url = "#contacto"
  weight = 70



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
